app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'], function () {
    //Route::resource('users', 'UserController');

	//index
	Route::get('/admin', ['as' => 'admin.index', 'uses' => 'Admin\AdminController@index']);
	Route::get('/index-admin', ['as' => 'auth.index-admin', 'uses' => 'Admin\AdminController@indexAdmin']);

	Route::get('auth-google/{auth?}', ['as' => 'auth-google', 'uses' => 'Admin\AssistenceController@getGoogleLogin']);
	
	Route::resource('assistence', 'Admin\AssistenceController');
	
	Route::get('assistences/logout-google', ['as' => 'logout-google', 'uses' => 'Admin\AssistenceController@getGoogleLogout']);

	Route::resource('type-product', 'App\TypeProductController');
	Route::resource('brands-attended', 'App\BrandsAttendedController');

	//Rotas para Assistencia request
	Route::resource('assistence-request', 'Admin\AssistenceRequestController', ['except' => ['create', 'store']]);
});

Route::resource('search-assistence', 'App\AssistenceController', ['except' => ['create', 'store', 'update', 'edit', 'destroy']]);

Route::get('/assistence-solicitation', ['as' => 'assistence-solicitation.create', 'uses' => 'App\AssistenceRequestController@create']);
Route::post('/assistence-solicitation', ['as' => 'assistence-solicitation.store', 'uses' => 'App\AssistenceRequestController@store']);

Route::get('/index', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);
Route::get('/', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);


//Authentication 
Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@login']);
Route::post('/login', ['as' => 'auth.authenticate', 'uses' => 'Auth\AuthController@authenticate']);

Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

app/Http/Controllers/App/BrandsAttendedController.php
<?php

namespace App\Http\Controllers\App;

use Illuminate\Http\Request;
use Domain\BrandsAttended\BrandsAttendedRequest;
use App\Http\Controllers\BaseController;
use Domain\BrandsAttended\BrandsAttendedRepositoryInterface as BrandsAttended;

class BrandsAttendedController extends BaseController
{
    protected $brandsAttendeds;

    public function __construct(BrandsAttended $brandsAttendeds)
    {
        $this->brandsAttendeds = $brandsAttendeds;
    }

    /**
     * Lista todas as brandsAttendeds e retorna para o Index
     *
     * @return Response
     */
    public function index()
    {
        $brandsAttendeds = $this->brandsAttendeds->index();

        return view('admin.brands-attendeds.index', compact('brandsAttendeds'));
    }

    /**
     * Abre o formulario para cadastro de brandsAttendeds
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.brands-attendeds.create');
    }

    /**
     * Cria uma nova brandsAttended
     *
     * @param  Request $request
     * @return Response
     */
    public function store(BrandsAttendedRequest $request)
    {
        $brandsAttended = $this->brandsAttendeds->save($request);

        return $this->backWithFlash("Tipo de produto foi cadastrado com Sucesso!");
    }

    /**
     * Lista uma brandsAttended especifica
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $brandsAttended = $this->brandsAttendeds->show($id);

        return view('admin.brands-attendeds.show', compact('brandsAttended'));
    }

    /**
     * Mostra a tela para editar uma brandsAttended especifica
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $brandsAttended = $this->brandsAttendeds->show($id);

        return view('admin.brands-attendeds.edit', compact('brandsAttended'));
    }

    /**
     * Altera uma brandsAttended especifica
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(BrandsAttendedRequest $request, $id)
    {
        $this->brandsAttendeds->save($request, $id);

        return $this->backWithFlash("O tipo de produto foi alterada com Sucesso!");
    }

    /**
     * Remove uma brandsAttended especifica
     *
     * @param  int $id
     * @return Response
     */
    public function destroy($id)
    {
        $this->brandsAttendeds->destroy($id);

        return $this->backWithFlash("Cadastro Excluido com Sucesso!", 'danger');
    }
}

resources/views/admin/brands-attendeds/create.blade.php
<div class="modal fade" id="create-brands-attended" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="ModalLabel">Criar Novo</h4>
            </div>
            {!! Form::open(['route' => 'brands-attended.store']) !!}
                <div class="modal-body">
                    {!! Form::textFieldM('description', 'Descrição') !!}
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-success">Salvar</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>

resources/views/admin/brands-attendeds/edit.blade.php
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalLabel">Editar</h4>
    </div>
    {!! Form::model($brandsAttended, [
            'method' => 'PUT',
            'route' => ['brands-attended.update', $brandsAttended->id
        ],
        'data-validate']) !!}
        <div class="modal-body">
            {!! Form::textFieldM('description', 'Descrição') !!}
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-success">Salvar</button>
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
    {!! Form::close() !!}
</div>

resources/views/admin/brands-attendeds/index.blade.php
@extends('layouts.default')
@section('title', 'Marcas Atendidas')
@section('content')

<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1>Marcas Atendidas</h1>
        </div>
        <div class="panel-body">
            <a href="" data-toggle="modal" data-target="#create-brands-attended" class="btn btn-success btn-raised">
                Criar novo Produto
            </a>

            <br/>
            <br/>
            <div class="table-responsive col-sm-12">
                <table class="display table data-table table-condensed">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Descrição</th>
                            <th>Gerenciar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($brandsAttendeds))

                            @foreach($brandsAttendeds as $brandsAttended)
                                <tr>
                                    <td>{{ $brandsAttended->id }}</td>
                                    <td>{{ $brandsAttended->description }}</td>
                                    <td>
                                        <a data-href="{{ route('brands-attended.edit', $brandsAttended->id) }}"
                                            class="btn btn-success btn-xs" data-target="#edit-brands-attended"
                                            href="" data-modal-open="" title="Editar">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                        {!!  Form::open(['route' => [
                                                    'brands-attended.destroy',
                                                    $brandsAttended->id
                                                ],
                                                'method' => 'DELETE',
                                                'data-id' => $brandsAttended->id ,
                                                'class' => 'form-horizontal',
                                                'style' => 'display: inline-block'
                                            ])
                                        !!}
        	                                <button data-id="{{ $brandsAttended->id }}"
                                                type="submit" class="btn btn-xs btn-danger" title="Excluir"
                                            >
        	                                    <i class="fa fa-remove"></i>
        	                                </button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br/>

<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                	<span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger btn-delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Deletar
                </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal editar produtos atendidos -->
<div class="modal fade" id="edit-brands-attended" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-md" role="document">
        
    </div>
</div>

<!-- Modal criar Protos atendidos -->
@include('admin.brands-attendeds.create')

@stop