app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'], function () {
    //Route::resource('users', 'UserController');

	//index
	Route::get('/admin', ['as' => 'admin.index', 'uses' => 'Admin\AdminController@index']);
	Route::get('/index-admin', ['as' => 'auth.index-admin', 'uses' => 'Admin\AdminController@indexAdmin']);

	Route::get('auth-google/{auth?}', ['as' => 'auth-google', 'uses' => 'Admin\AssistenceController@getGoogleLogin']);
	
	Route::resource('assistence', 'Admin\AssistenceController');
	
	Route::get('assistences/logout-google', ['as' => 'logout-google', 'uses' => 'Admin\AssistenceController@getGoogleLogout']);

	Route::resource('type-product', 'App\TypeProductController');
	Route::resource('brands-attended', 'App\BrandsAttendedController');

	//Rotas para Assistencia request
	Route::resource('assistence-request', 'Admin\AssistenceRequestController', ['except' => ['create', 'store']]);
});

Route::resource('search-assistence', 'App\AssistenceController', ['except' => ['create', 'store', 'update', 'edit', 'destroy']]);

Route::get('/assistence-solicitation', ['as' => 'assistence-solicitation.create', 'uses' => 'App\AssistenceRequestController@create']);
Route::post('/assistence-solicitation', ['as' => 'assistence-solicitation.store', 'uses' => 'App\AssistenceRequestController@store']);

Route::get('/index', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);
Route::get('/', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);


//Authentication 
Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@login']);
Route::post('/login', ['as' => 'auth.authenticate', 'uses' => 'Auth\AuthController@authenticate']);

Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

app/Http/Controllers/Admin/AssistenceRequestController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Domain\AssistenceRequest\AssistenceRequestRequest;
use App\Http\Controllers\BaseController;
use Domain\AssistenceRequest\AssistenceRequestRepositoryInterface as AssistenceRequest;
use Domain\TypeProduct\TypeProductRepositoryInterface as TypeProduct;
use Domain\BrandsAttended\BrandsAttendedRepositoryInterface as BrandsAttended;

class AssistenceRequestController extends BaseController
{
    protected $typeProducts;
    protected $brandsAttendeds;
    protected $assistenceRequests;


    public function __construct(
            AssistenceRequest $assistenceRequests,
            TypeProduct $typeProducts,
            BrandsAttended $brandsAttendeds
        )
    {
        $this->typeProducts = $typeProducts;
        $this->brandsAttendeds = $brandsAttendeds;
        $this->assistenceRequests = $assistenceRequests;
    }

    /**
     * Lista todas as assistenceRequests e retorna para o Index
     *
     * @return Response
     */
    public function index()
    {
        $assistences = $this->assistenceRequests->index();

        return view('admin.assistence-requests.index', compact('assistences'));
    }

    /**
     * Lista uma assistenceRequest especifica
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        return $assistenceRequest = $this->assistenceRequests->show($id);

        //return view('admin.assistence-requests.show', compact('assistenceRequest'));
    }

    /**
     * Mostra a tela para editar uma assistenceRequest especifica
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $typeProducts = $this->typeProducts->listForSelect();
        $brandsAttendeds = $this->brandsAttendeds->listForSelect();

        $assistencia = $this->assistenceRequests->show($id);

        return view('admin.assistence-requests.edit', compact('assistencia', 'typeProducts', 'brandsAttendeds'));
    }

    /**
     * Altera uma assistenceRequest especifica
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(AssistenceRequestRequest $request, $id)
    {
        $this->assistenceRequests->save($request, $id);

        return $this->backWithFlash("O tipo de produto foi alterada com Sucesso!");
    }

    /**
     * Remove uma assistenceRequest especifica
     *
     * @param  int $id
     * @return Response
     */
    public function destroy(Request $request, $id)
    {
        $destroy = $this->assistenceRequests->destroy($id);

        if($request->ajax()) {
            return 'destroyed';
        }

        return $this->backWithFlash("Cadastro Excluido com Sucesso!", 'danger');
    }
}

app/Http/Controllers/App/AssistenceRequestController.php
<?php

namespace App\Http\Controllers\App;

use Illuminate\Http\Request;
use Domain\AssistenceRequest\AssistenceRequestRequest;
use App\Http\Controllers\BaseController;
use Domain\AssistenceRequest\AssistenceRequestRepositoryInterface as AssistenceRequest;
use Domain\TypeProduct\TypeProductRepositoryInterface as TypeProduct;
use Domain\BrandsAttended\BrandsAttendedRepositoryInterface as BrandsAttended;

class AssistenceRequestController extends BaseController
{
    protected $typeProducts;
    protected $brandsAttendeds;
    protected $assistenceRequests;


    public function __construct(
            AssistenceRequest $assistenceRequests,
            TypeProduct $typeProducts,
            BrandsAttended $brandsAttendeds
        )
    {
        $this->typeProducts = $typeProducts;
        $this->brandsAttendeds = $brandsAttendeds;
        $this->assistenceRequests = $assistenceRequests;
    }

    /**
     * Abre o formulario para cadastro de assistenceRequests
     *
     * @return Response
     */
    public function create()
    {
        $typeProducts = $this->typeProducts->listForSelect();
        $brandsAttendeds = $this->brandsAttendeds->listForSelect();

        return view('admin.assistence-requests.create', compact('typeProducts', 'brandsAttendeds'));
    }

    /**
     * Cria uma nova assistenceRequest
     *
     * @param  Request $request
     * @return Response
     */
    public function store(AssistenceRequestRequest $request)
    {
        $assistenceRequest = $this->assistenceRequests->save($request);

        return $this->routeRedirectWithFlash('index', '', "Solicitação de cadastro realizado com Sucesso!");
    }
}

resources/views/admin/assistence-requests/create.blade.php
@extends('layouts.default')
@section('title', 'Assistências')
@section('content')

<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1><i class="fa fa-gears"></i> Cadastro de Assistência</h1>
        </div>
        {!! Form::open(['route' => 'assistence-solicitation.store']) !!}
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                            {!! Form::textFieldM('name', 'Nome da Assistência') !!}
                            {!! Form::textFieldM('location', 'Endereço') !!}
                            <div class="row">
                                <div class="col-sm-4">
                                    {!! Form::selectMultipleFieldM(
                                        'typeProduct',
                                        'Tipos de produtos',
                                        $typeProducts, ['data-selectize'])
                                    !!}
                                </div>
                                <div class="col-sm-4">
                                    {!! Form::selectMultipleFieldM('brandsAttendedWarranty',
                                        'Marcas Atendidas (Garantia)',
                                        $brandsAttendeds, ['data-selectize'])
                                    !!}
                                </div>
                                <div class="col-sm-4">
                                    {!! Form::selectMultipleFieldM('brandsAttended',
                                        'Marcas Atendidas (Fora de garantia)',
                                        $brandsAttendeds, ['data-selectize'])
                                    !!}
                                </div>
                            </div>
                            <div class="mar-ver pad-ver row">
                                <div class="col-sm-4">
                                    {!! Form::radioInline('category', 'Tipo', [
                                            'AUTORIZADA' => 'Autorizada',
                                            'ESPECIALIZADA' => 'Especializada'
                                        ], 'AUTORIZADA')
                                    !!}
                                </div>
                                <div class="col-sm-4">
                                    {!! Form::textFieldM('fone', 'Telefone') !!}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <label>Horário de funcionamento</label>
                                    {!! Form::selectField('businessHoursDate',
                                        'Selecione os dias',
                                        [   
                                            'SEG-SEX' => 'Segunda á Sexta',
                                            'SEG-SAB' => 'Segunda á Sábado',
                                            'DOM-DOM' => 'Domingo á Domingo'
                                        ], ['data-selectize'])
                                    !!}
                                </div>
                                <div style="margin-top: 35px" class="col-sm-4">
                                    {!! Form::textField(
                                            'hoursStart',
                                            'Abre as:'
                                        )
                                    !!}
                                </div>
                                <div style="margin-top: 35px" class="col-sm-4">
                                    {!! Form::textField(
                                            'hoursEnd',
                                            'Fecha as:'
                                        )
                                    !!}
                                </div>
                            </div>

                            {!! Form::textareaFieldM('info', 'Informações gerais') !!}

                            
                            
                    </div>
                </div>
            </div>
            <div class="panel-footer">
                <input type="submit" class="btn btn-raised btn-success" value="Salvar"/>
                <a href="{{ route('auth-google') }}" class="btn btn-raised btn-danger">
                    Voltar
                </a>
            </div>
        {!! Form::close() !!}
    </div>

</div>

@stop

resources/views/admin/assistence-requests/edit.blade.php
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalLabel">Aprovar Assistência</h4>
    </div>
        {!! Form::open(['route' => 'assistence.store']) !!}
            <div class="modal-body">
                {!! Form::textFieldM('name', 'Nome da Assistência', $assistencia->name) !!}
                {!! Form::textFieldM('location', 'Endereço', $assistencia->location) !!}
                <div class="row">
                    <div class="col-sm-4">
                        {!! Form::selectMultipleFieldM(
                            'typeProduct',
                            'Tipos de produtos',
                            $typeProducts, ['data-selectize'], json_decode($assistencia->typeProduct))
                        !!}
                    </div>
                    <div class="col-sm-4">
                        {!! Form::selectMultipleFieldM('brandsAttendedWarranty',
                            'Marcas Atendidas (Garantia)',
                            $brandsAttendeds, ['data-selectize'], json_decode($assistencia->brandsAttendedWarranty))
                        !!}
                    </div>
                    <div class="col-sm-4">
                        {!! Form::selectMultipleFieldM('brandsAttended',
                            'Marcas Atendidas (Fora de garantia)',
                            $brandsAttendeds, ['data-selectize'], json_decode($assistencia->brandsAttended))
                        !!}
                    </div>
                </div>
                <div class="pad-ver row">
                    <div class="col-sm-6">
                        {!! Form::radioInlineM('typeAssist', 'Tipo', [
                                'AUTORIZADA' => ' Autorizada',
                                'ESPECIALIZADA' => ' Especializada'
                            ], $assistencia->category)
                        !!}
                    </div>
                    <div class="col-sm-6">
                        {!! Form::textFieldM('fone', 'Telefone', $assistencia->fone) !!}
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-4">
                        <label>Dias e horários de funcionamento</label>
                        {!! Form::selectField('businessHoursDate',
                            'Selecione os dias',
                            [   
                                'SEG-SEX' => 'Segunda á Sexta',
                                'SEG-SAB' => 'Segunda á Sábado',
                                'DOM-DOM' => 'Domingo á Domingo'
                            ], ['data-selectize'], $assistencia->businessHoursDate)
                        !!}
                    </div>
                    <div style="margin-top: 35px" class="col-sm-4">
                        {!! Form::textField(
                                'hoursStart',
                                'Abre as:',
                                $assistencia->hoursStart
                            )
                        !!}
                    </div>
                    <div style="margin-top: 35px" class="col-sm-4">
                        {!! Form::textField(
                                'hoursEnd',
                                'Fecha as:',
                                $assistencia->hoursEnd
                            )
                        !!}
                    </div>
                </div>
                {!! Form::textareaField('info', 'Informações gerais', $assistencia->info) !!}
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-success"
                    data-aprove-delete="{{ route('assistence-request.destroy', $assistencia->id) }}">
                    Salvar
                </button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
            </div>
        {!! Form::close() !!}
</div>

resources/views/admin/assistence-requests/index.blade.php
@extends('layouts.default')
@section('title', 'Assistências')
@section('content')

<div class="container">
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1>Aprovar assistências</h1>
            <p>Assistencias para aprovar</p>
        </div>
        <div class="panel-body">
            

            <br/>
            <br/>
            <div class="table-responsive col-sm-12">
                <table id ="table-pessoas" class="display table data-table table-condensed">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Localização</th>
                            <th>Atende</th>
                            <th>Gerenciar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if($assistences->count())

                            @foreach($assistences as $assistencia)
                                <tr>
                                    <td>{{ $assistencia->name }}</td>
                                    <td>{{ $assistencia->category }}</td>
                                    <td>{{ $assistencia->location }}</td>
                                    <td>{{ $assistencia->present()->businessHours }}</td>
                                    <td>
                                        <a data-href="{{ route('assistence-request.edit', $assistencia->id) }}"
                                            class="btn btn-success btn-xs" data-target="#aprove-assistence-request"
                                            href="" data-modal-open="" title="Editar">
                                            <i class="fa fa-check"></i>
                                        </a>
                                        {!!  Form::open([
                                                'route' => [
                                                    'assistence-request.destroy',
                                                    $assistencia->id
                                                ],
                                                    'method' => 'DELETE',
                                                    'data-id' => $assistencia->id ,
                                                    'class' => 'form-horizontal',
                                                    'style' => 'display: inline-block'
                                                ]
                                            )
                                        !!}
        	                                <button data-id="{{ $assistencia->id }}"
                                                type="submit" class="btn btn-xs btn-danger" title="Excluir"
                                            >
        	                                    <i class="fa fa-remove"></i>
        	                                </button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<br/>

<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                	<span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger btn-delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Deletar
                </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal editar Assistencias -->
<div class="modal fade" id="aprove-assistence-request" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        
    </div>
</div>

@stop