app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'], function () {
    //Route::resource('users', 'UserController');

	//index
	Route::get('/admin', ['as' => 'admin.index', 'uses' => 'Admin\AdminController@index']);
	Route::get('/index-admin', ['as' => 'auth.index-admin', 'uses' => 'Admin\AdminController@indexAdmin']);

	Route::get('auth-google/{auth?}', ['as' => 'auth-google', 'uses' => 'Admin\AssistenceController@getGoogleLogin']);
	
	Route::resource('assistence', 'Admin\AssistenceController');
	
	Route::get('assistences/logout-google', ['as' => 'logout-google', 'uses' => 'Admin\AssistenceController@getGoogleLogout']);

	Route::resource('type-product', 'App\TypeProductController');
	Route::resource('brands-attended', 'App\BrandsAttendedController');

	//Rotas para Assistencia request
	Route::resource('assistence-request', 'Admin\AssistenceRequestController', ['except' => ['create', 'store']]);
});

Route::resource('search-assistence', 'App\AssistenceController', ['except' => ['create', 'store', 'update', 'edit', 'destroy']]);

Route::get('/assistence-solicitation', ['as' => 'assistence-solicitation.create', 'uses' => 'App\AssistenceRequestController@create']);
Route::post('/assistence-solicitation', ['as' => 'assistence-solicitation.store', 'uses' => 'App\AssistenceRequestController@store']);

Route::get('/index', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);
Route::get('/', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);


//Authentication 
Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@login']);
Route::post('/login', ['as' => 'auth.authenticate', 'uses' => 'Auth\AuthController@authenticate']);

Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

app/Http/Controllers/Admin/AssistenceController.php
<?php
namespace App\Http\Controllers\Admin;

use Auth;
use Requests;
use Google_Client;
use Hybrid_Auth;
use Hybrid_Endpoint;
use Illuminate\Http\Request;
use Domain\User\UserRequest;
use App\Http\Controllers\BaseController;
use Domain\User\UserRepositoryInterface as User;
use Domain\TypeProduct\TypeProductRepositoryInterface as TypeProduct;
use Domain\BrandsAttended\BrandsAttendedRepositoryInterface as BrandsAttended;

class AssistenceController extends BaseController
{
    protected $users;
    protected $typeProducts;
    protected $brandsAttendeds;

    public function __construct(User $users, TypeProduct $typeProducts, BrandsAttended $brandsAttendeds)
    {
        $this->users = $users;
        $this->loggedUser = Auth::user();
        $this->typeProducts = $typeProducts;
        $this->brandsAttendeds = $brandsAttendeds;
        $this->tableAssistencesId = "1aPLJfYAPlL3L2KVVC-FyZaspqnpv4MWK-dYpgbPS";
    }

    /**
     * Mostra a tela inicial
     *
     * @return Response
     */ 
    public function index()
    {
        $url = "https://www.googleapis.com/fusiontables/v2/query?";
        $url .= "sql=SELECT ROWID, name, category, Location, typeProduct, brandsAttended, " .
            "brandsAttendedWarranty, businessHoursDate, hoursStart, hoursEnd, active ";
        $url .= "FROM $this->tableAssistencesId&key=AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc";

        $assistences = [];
        $headers = ['Accept' => 'application/json'];

        //$options = [    
            //'sql' => "SELECT * FROM $this->tableAssistencesId",
            //'key' => 'AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc'
        //];

        $response = Requests::get($url, $headers);

        if($response->success) {

            $assistenciasJson = json_decode($response->body);

            foreach ($assistenciasJson->rows as $key => $assistenciaJson) {

                $assistences[] = collect(array_combine($assistenciasJson->columns, $assistenciaJson));
            }
        }

        return view('admin.assistence.index', compact('assistences'));
    }

    /**
     * Abre o formulario para cadastro de pessoas
     *
     * @return Response
     */
    public function create()
    {
        $typeProducts = $this->typeProducts->listForSelect();
        $brandsAttendeds = $this->brandsAttendeds->listForSelect();

        return view('admin.assistence.create', compact('typeProducts', 'brandsAttendeds'));
    }

    /**
     * Cria uma nova pessoa
     *pessoas
     * @param  Request $request
     * @return Response
     */
    public function store(Request $request)
    {  
        $request->typeProduct = $request->typeProduct ? json_encode($request->typeProduct) : null;
        $request->brandsAttended = $request->brandsAttended ? json_encode($request->brandsAttended) : null;
        $request->brandsAttendedWarranty = $request->brandsAttendedWarranty ?
            json_encode($request->brandsAttendedWarranty) : null;

        $request->active = 1;

        if(is_null($this->loggedUser->tokenGoogle)) {
            return 'pegar o token';
        }
        $token = 'Bearer ' . $this->loggedUser->tokenGoogle;

        $url = "https://www.googleapis.com/fusiontables/v2/query";

        $headers = [
            'Accept' => 'application/json',
            'Authorization' => $token
        ];

        $optionsAssistence = "(name,category,Location,info,typeProduct,brandsAttended," .
            "brandsAttendedWarranty,fone,active,businessHoursDate,hoursStart,hoursEnd ) " .
            "VALUES ";

        $optionsAssistence .= "(
            '$request->name',
            '$request->typeAssist',
            '$request->location',
            '$request->info',
            '$request->typeProduct',
            '$request->brandsAttended',
            '$request->brandsAttendedWarranty',
            '$request->fone',
            '$request->active',
            '$request->businessHoursDate',
            '$request->hoursStart',
            '$request->hoursEnd'
        )";

        $arry['sql'] = "INSERT INTO $this->tableAssistencesId $optionsAssistence;";
 
        $response = Requests::post($url, $headers, $arry);

        if($response->success) {
            return $this->routeRedirectWithFlash('auth-google', '', "Assistência cadastrada com Sucesso!");
        } else {
            dd('Erro:', $response);
        }
        return $this->backWithFlash("Ocorreu algum erro", 'danger');
    }
    
    /**
     * Lista uma assistencia especifica.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $url = "https://www.googleapis.com/fusiontables/v2/query?";
        $url .= "sql=SELECT ROWID, name, category, Location, typeProduct, brandsAttended, " .
            "brandsAttendedWarranty, fone, info, active, businessHoursDate, hoursStart, hoursEnd ";
        $url .= "FROM $this->tableAssistencesId WHERE rowid=$id&key=AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc";


        $assistences = [];
        $headers = ['Accept' => 'application/json'];

        $response = Requests::get($url, $headers);

        if($response->success) {

            $assistenciasJson = json_decode($response->body);
            foreach ($assistenciasJson->rows as $key => $assistenciaJson) {

                $assistencia[] = collect(array_combine($assistenciasJson->columns, $assistenciaJson));
            }
            $assistencia = $assistencia[0];
        } else {
            dd('Erro:', $response);
        }

        if($assistencia['typeProduct']) {
            $assistencia['typeProduct'] = $this->typeProducts
                ->index()
                ->whereIn('id', array_map('intval', json_decode($assistencia['typeProduct'])))
                ->pluck('description');

            $assistencia['typeProduct'] = implode(', ', $assistencia['typeProduct']->all());
        }

        if($assistencia['brandsAttended']) {
            $assistencia['brandsAttended'] = $this->brandsAttendeds
            ->index()
            ->whereIn('id', array_map('intval', json_decode($assistencia['brandsAttended'])))
            ->pluck('description');

            $assistencia['brandsAttended'] = implode(', ', $assistencia['brandsAttended']->all());
        }

        if($assistencia['brandsAttendedWarranty']) {
            $assistencia['brandsAttendedWarranty'] = $this->brandsAttendeds
                ->index()
                ->whereIn('id', array_map('intval', json_decode($assistencia['brandsAttendedWarranty'])))
                ->pluck('description');

            $assistencia['brandsAttendedWarranty'] = implode(', ', $assistencia['brandsAttendedWarranty']->all());
        }

        return view('admin.assistence.search-show', compact('assistencia', 'typeProducts', 'brandsAttendeds'));
    }

    /**
     * Mostra a tela para editar uma pessoa especifica
     *
     * @param  int $id
     * @return Response
     */
    public function edit($id)
    {
        $url = "https://www.googleapis.com/fusiontables/v2/query?";
        $url .= "sql=SELECT ROWID, name, category, Location, typeProduct, brandsAttended, " .
            "brandsAttendedWarranty, fone, info, active, businessHoursDate, hoursStart, hoursEnd ";
        $url .= "FROM $this->tableAssistencesId WHERE rowid=$id&key=AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc";


        $assistences = [];
        $headers = ['Accept' => 'application/json'];

        //$options = [    
            //'sql' => "SELECT * FROM $this->tableAssistencesId",
            //'key' => 'AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc'
        //];

        $response = Requests::get($url, $headers);

            //dd($response);
        if($response->success) {

            $assistenciasJson = json_decode($response->body);
            foreach ($assistenciasJson->rows as $key => $assistenciaJson) {

                $assistencia[] = collect(array_combine($assistenciasJson->columns, $assistenciaJson));
            }
            $assistencia = $assistencia[0];
        } else {
            dd('Erro:', $response);
        }

        $typeProducts = $this->typeProducts->listForSelect();
        $brandsAttendeds = $this->brandsAttendeds->listForSelect();

        return view('admin.assistence.edit', compact('assistencia', 'typeProducts', 'brandsAttendeds'));
    }

    /**
     * Altera uma pessoa especifica
     *
     * @param  Request $request
     * @param  int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $request->typeProduct = $request->typeProduct ? json_encode($request->typeProduct) : null;
        $request->brandsAttended = $request->brandsAttended ? json_encode($request->brandsAttended) : null;
        $request->brandsAttendedWarranty = $request->brandsAttendedWarranty ? json_encode($request->brandsAttendedWarranty) : null;

        if(is_null($this->loggedUser->tokenGoogle)) {
            return 'pegar o token';
        }
        $token = 'Bearer ' . $this->loggedUser->tokenGoogle;

        $url = "https://www.googleapis.com/fusiontables/v2/query";

        $headers = [
            'Accept' => 'application/json',
            'Authorization' => $token
        ];

        $optionsAssistence = "name = '$request->name',
            category = '$request->typeAssist',
            Location = '$request->location',
            info = '$request->info',
            typeProduct = '$request->typeProduct',
            brandsAttended = '$request->brandsAttended',
            brandsAttendedWarranty = '$request->brandsAttendedWarranty',
            fone = '$request->fone',
            active = '$request->active',
            businessHoursDate = '$request->businessHoursDate',
            hoursStart = '$request->hoursStart',
            hoursEnd = '$request->hoursEnd'
        ";

        $arry['sql'] = "UPDATE $this->tableAssistencesId SET $optionsAssistence WHERE ROWID = '$id';";
 
        $response = Requests::post($url, $headers, $arry);
        if($response->success) {

app/Http/Controllers/App/AssistenceController.php
<?php
namespace App\Http\Controllers\App;

use Auth;
use Requests;
use Google_Client;
use Hybrid_Auth;
use Hybrid_Endpoint;
use Illuminate\Http\Request;
use Domain\User\UserRequest;
use App\Http\Controllers\BaseController;
use Domain\User\UserRepositoryInterface as User;
use Domain\TypeProduct\TypeProductRepositoryInterface as TypeProduct;
use Domain\BrandsAttended\BrandsAttendedRepositoryInterface as BrandsAttended;

class AssistenceController extends BaseController
{
    protected $users;
    protected $typeProducts;
    protected $brandsAttendeds;

    public function __construct(User $users, TypeProduct $typeProducts, BrandsAttended $brandsAttendeds)
    {
        $this->users = $users;
        $this->loggedUser = Auth::user();
        $this->typeProducts = $typeProducts;
        $this->brandsAttendeds = $brandsAttendeds;
        $this->tableAssistencesId = "1aPLJfYAPlL3L2KVVC-FyZaspqnpv4MWK-dYpgbPS";
    }

    /**
     * Mostra a tela inicial
     *
     * @return Response
     */ 
    public function index()
    {
        $url = "https://www.googleapis.com/fusiontables/v2/query?";
        $url .= "sql=SELECT ROWID, name, category, Location, typeProduct, brandsAttended, " .
            "brandsAttendedWarranty, businessHoursDate, hoursStart, hoursEnd, active ";
        $url .= "FROM $this->tableAssistencesId&key=AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc";

        $assistences = [];
        $headers = ['Accept' => 'application/json'];

        //$options = [    
            //'sql' => "SELECT * FROM $this->tableAssistencesId",
            //'key' => 'AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc'
        //];

        $response = Requests::get($url, $headers);

        if($response->success) {

            $assistenciasJson = json_decode($response->body);

            foreach ($assistenciasJson->rows as $key => $assistenciaJson) {

                $assistences[] = collect(array_combine($assistenciasJson->columns, $assistenciaJson));
            }
        }

        return view('admin.assistence.search-index', compact('assistences'));
    }

    /**
     * Lista uma assistencia especifica.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $url = "https://www.googleapis.com/fusiontables/v2/query?";
        $url .= "sql=SELECT ROWID, name, category, Location, typeProduct, brandsAttended, " .
            "brandsAttendedWarranty, fone, info, active, businessHoursDate, hoursStart, hoursEnd ";
        $url .= "FROM $this->tableAssistencesId WHERE rowid=$id&key=AIzaSyA9Up-4eYIsGn1cwwfMh-Zy1PAH-qPZJEc";


        $assistences = [];
        $headers = ['Accept' => 'application/json'];

        $response = Requests::get($url, $headers);

        if($response->success) {

            $assistenciasJson = json_decode($response->body);
            foreach ($assistenciasJson->rows as $key => $assistenciaJson) {

                $assistencia[] = collect(array_combine($assistenciasJson->columns, $assistenciaJson));
            }
            $assistencia = $assistencia[0];
        } else {
            dd('Erro:', $response);
        }

        if($assistencia['typeProduct']) {
            $assistencia['typeProduct'] = $this->typeProducts
                ->index()
                ->whereIn('id', array_map('intval', json_decode($assistencia['typeProduct'])))
                ->pluck('description');

            $assistencia['typeProduct'] = implode(', ', $assistencia['typeProduct']->all());
        }

        if($assistencia['brandsAttended']) {
            $assistencia['brandsAttended'] = $this->brandsAttendeds
            ->index()
            ->whereIn('id', array_map('intval', json_decode($assistencia['brandsAttended'])))
            ->pluck('description');

            $assistencia['brandsAttended'] = implode(', ', $assistencia['brandsAttended']->all());
        }

        if($assistencia['brandsAttendedWarranty']) {
            $assistencia['brandsAttendedWarranty'] = $this->brandsAttendeds
                ->index()
                ->whereIn('id', array_map('intval', json_decode($assistencia['brandsAttendedWarranty'])))
                ->pluck('description');

            $assistencia['brandsAttendedWarranty'] = implode(', ', $assistencia['brandsAttendedWarranty']->all());
        }

        return view('admin.assistence.search-show', compact('assistencia', 'typeProducts', 'brandsAttendeds'));
    }
}

resources/views/admin/assistence/create.blade.php
@extends('layouts.default')
@section('title', 'Assistências')
@section('content')

<div class="container">
    
    <div class="panel panel-info">
        <div class="panel-heading">
            <h1>Assistências</h1>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-10">
                    {!! Form::open(['route' => 'assistence.store']) !!}
                        {!! Form::textFieldM('name', 'Nome da Assistência') !!}
                        {!! Form::textFieldM('location', 'Endereço') !!}
                        <div class="row">
                            <div class="col-sm-4">
                                {!! Form::radioInline('typeAssist', 'Tipo', [
                                        'AUTORIZADA' => 'Autorizada',
                                        'ESPECIALIZADA' => 'Especializada'
                                    ], 'AUTORIZADA')
                                !!}
                            </div>
                            <div class="col-sm-4">
                                {!! Form::textFieldM('fone', 'Telefone') !!}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                {!! Form::selectMultipleFieldM(
                                    'typeProduct',
                                    'Tipos de produtos',
                                    $typeProducts, ['data-selectize'])
                                !!}
                            </div>
                            <div class="col-sm-4">
                                {!! Form::selectMultipleFieldM('brandsAttendedWarranty',
                                    'Marcas Atendidas (Garantia)',
                                    $brandsAttendeds, ['data-selectize'])
                                !!}
                            </div>
                            <div class="col-sm-4">
                                {!! Form::selectMultipleFieldM('brandsAttended',
                                    'Marcas Atendidas (Fora de garantia)',
                                    $brandsAttendeds, ['data-selectize'])
                                !!}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4">
                                <label>Dias e horários de funcionamento</label>
                                {!! Form::selectField('businessHoursDate',
                                    'Selecione os dias',
                                    [   
                                        'SEG-SEX' => 'Segunda á Sexta',
                                        'SEG-SAB' => 'Segunda á Sábado',
                                        'DOM-DOM' => 'Domingo á Domingo'
                                    ], ['data-selectize'])
                                !!}
                            </div>
                            <div style="margin-top: 35px" class="col-sm-4">
                                {!! Form::textField(
                                        'hoursStart',
                                        'Abre as:'
                                    )
                                !!}
                            </div>
                            <div style="margin-top: 35px" class="col-sm-4">
                                {!! Form::textField(
                                        'hoursEnd',
                                        'Fecha as:'
                                    )
                                !!}
                            </div>
                        </div>
                        
                        {!! Form::textareaFieldM('info', 'Informações gerais') !!}

                        <input type="submit" class="btn btn-raised btn-success" value="Salvar"/>
                        <a href="{{ route('auth-google') }}" class="btn btn-raised btn-danger">
                            Voltar
                        </a>
                        
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>

</div>

@stop

resources/views/admin/assistence/index.blade.php
@extends('layouts.default')
@section('title', 'Assistências')
@section('content')

<div class="container">

    <div class="panel panel-info">
        <div class="panel-heading">
            <h1><i class="fa fa-gears"></i> Assistências</h1>
        </div>
        <div class="panel-body">
            <a href="{{ route('assistence.create') }}" class="btn btn-success btn-raised">
                <i class="fa fa-plus"></i> Criar nova Assistência
            </a>
            <div class="table-responsive col-sm-12">
                <table id ="table-pessoas" class="display table data-table table-condensed">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Gerenciar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($assistences))

                            @foreach($assistences as $assistencia)
                                <tr>
                                    <td>{{ $assistencia['name'] }}</td>
                                    <td>{{ $assistencia['category'] }}</td>
                                    <td>
                                        <a data-href="{{ route('assistence.show', $assistencia['rowid']) }}"
                                            class="btn btn-info btn-xs" data-target="#show-assistence-modal"
                                            href="" data-modal-open="" title="Ver Assistência">
                                            <i class="fa fa-search"></i>
                                        </a>
                                        <a data-href="{{ route('assistence.edit', $assistencia['rowid']) }}"
                                            class="btn btn-success btn-xs" data-target="#edit-assistence-modal"
                                            href="" data-modal-open="" title="Editar">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                        {!!  Form::open(['route' => ['assistence.destroy', $assistencia['rowid']], 'method' => 'DELETE',
                                            'data-id' => $assistencia['rowid'] , 'class' => 'form-horizontal','style' => 'display: inline-block'])
                                        !!}
        	                                <button data-id="{{ $assistencia['rowid'] }}"
                                                type="submit" class="btn btn-xs btn-danger" title="Excluir"
                                            >
        	                                    <i class="fa fa-remove"></i>
        	                                </button>
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>
<br/>

<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                	<span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger btn-delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Deletar
                </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal editar Assistencias -->
<div class="modal fade" id="edit-assistence-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        
    </div>
</div>

<!-- Modal editar Assistencias -->
<div class="modal fade" id="show-assistence-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        
    </div>
</div>

@stop

resources/views/admin/assistence/search-index.blade.php
@extends('layouts.default')
@section('title', 'Assistências')
@section('content')

<div class="container">

    <div class="panel panel-info">
        <div class="panel-heading">
            <h1><i class="fa fa-gears"></i> Buscar Assistências</h1>
        </div>
        <div class="panel-body">
            <div class="table-responsive col-sm-12">
                <table id ="table-pessoas" class="display table data-table table-condensed">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Tipo</th>
                            <th>Endereço</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if(!empty($assistences))

                            @foreach($assistences as $assistencia)
                                <tr>
                                    <td>{{ $assistencia['name'] }}</td>
                                    <td>{{ $assistencia['category'] }}</td>
                                    <td>{{ strlen($assistencia['Location']) >= 55 ?
                                        substr($assistencia['Location'], 0, 55) . ' ...' :
                                        $assistencia['Location']
                                    }}
                                    </td>
                                    <td>
                                        <a data-href="{{ route('search-assistence.show', $assistencia['rowid']) }}"
                                            class="btn btn-info btn-xs" data-target="#show-assistence-modal"
                                            href="" data-modal-open="" title="Ver Assistência">
                                            <i class="fa fa-search"></i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        @endif
                    </tbody>
                </table>
            </div>

        </div>
    </div>

</div>
<br/>

<div class="modal fade" id="modal-delete" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                	<span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Excluir</h4>
            </div>
            <div class="modal-body">
                <p>Deseja realmente excluir ?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-danger btn-delete">
                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Deletar
                </button>
                <button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<!-- Modal editar Assistencias -->
<div class="modal fade" id="show-assistence-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        
    </div>
</div>

@stop

resources/views/admin/assistence/search-show.blade.php
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title" id="ModalLabel">Assistência: {{ $assistencia['name'] }}</h4>
    </div>
        <div class="modal-body">
            <p><strong>Categoria: </strong>{{ $assistencia['category'] }}</p>
            <p><strong>Endereço: </strong>{{ $assistencia['Location'] }}</p>
            <p><strong>Telefone: </strong>{{ $assistencia['fone'] }}</p>
            <p><strong>Tipos de produtos: </strong>
                {{ $assistencia['typeProduct'] }}
            </p>
            <p><strong>Marcas Atendidas (Garantia): </strong>
                {{ $assistencia['brandsAttendedWarranty'] }}
            </p>
            <p><strong>Marcas Atendidas (Fora de garantia): </strong>
                {{ $assistencia['brandsAttended'] }}
            </p>
            <p><strong>Horario de Funcionamento: </strong>
                {{ $assistencia['businessHoursDate'] . ' ' .
                    $assistencia['hoursStart'] . ' ás ' .
                    $assistencia['hoursEnd']
                }}
            </p>
            <p><strong>Informações gerais: </strong>{{ $assistencia['info'] }}</p>

            <a href="#">Ver no Mapa</a>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
        </div>
</div>