app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'], function () {
    //Route::resource('users', 'UserController');

	//index
	Route::get('/admin', ['as' => 'admin.index', 'uses' => 'Admin\AdminController@index']);
	Route::get('/index-admin', ['as' => 'auth.index-admin', 'uses' => 'Admin\AdminController@indexAdmin']);

	Route::get('auth-google/{auth?}', ['as' => 'auth-google', 'uses' => 'Admin\AssistenceController@getGoogleLogin']);
	
	Route::resource('assistence', 'Admin\AssistenceController');
	
	Route::get('assistences/logout-google', ['as' => 'logout-google', 'uses' => 'Admin\AssistenceController@getGoogleLogout']);

	Route::resource('type-product', 'App\TypeProductController');
	Route::resource('brands-attended', 'App\BrandsAttendedController');

	//Rotas para Assistencia request
	Route::resource('assistence-request', 'Admin\AssistenceRequestController', ['except' => ['create', 'store']]);
});

Route::resource('search-assistence', 'App\AssistenceController', ['except' => ['create', 'store', 'update', 'edit', 'destroy']]);

Route::get('/assistence-solicitation', ['as' => 'assistence-solicitation.create', 'uses' => 'App\AssistenceRequestController@create']);
Route::post('/assistence-solicitation', ['as' => 'assistence-solicitation.store', 'uses' => 'App\AssistenceRequestController@store']);

Route::get('/index', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);
Route::get('/', ['as' => 'index', 'uses' => 'Auth\AuthController@index']);


//Authentication 
Route::get('/login', ['as' => 'auth.login', 'uses' => 'Auth\AuthController@login']);
Route::post('/login', ['as' => 'auth.authenticate', 'uses' => 'Auth\AuthController@authenticate']);

Route::get('/logout', ['as' => 'auth.logout', 'uses' => 'Auth\AuthController@logout']);

resources/views/layouts/css.blade.php
<link rel="stylesheet" href="{{ asset('assets/css/style.min.css') }}" type="text/css">

resources/views/layouts/default.blade.php
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@yield('description', '')">
    <meta name="keywords" content="@yield('keywords' , '')">
    <meta name="author" content="Gabriel Silva de Morais">
    <meta name="ROBOTS" content="INDEX,FOLLOW">
    <title>Let's Repair | @yield('title', 'Lets Repair')</title>
    @include('layouts.css')
</head>


<body>
    {!! Html::flash() !!}
    {{--dd(!Request::is('index'))--}}
    @if($current_user)
        @include('layouts.navbar')
    @else
        @include('layouts.navbarApp')
    @endif

    @yield('content')

    @include('layouts.js')
</body>

</html>

resources/views/layouts/js.blade.php
<script src="{{ asset('assets/js/libs.min.js') }}" > </script>

<script src="{{ asset('assets/js/app.min.js') }}" > </script>
<script
	src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB3eIgwMkqQtZuM7iVJi2is6EoktemIZ8E&signed_in=true&libraries=places&callback=initMap" async defer>
</script>

resources/views/layouts/navbar.blade.php
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand text-bold" href="{{ url('index-admin') }}">Let's Repair</a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
        <ul class="nav navbar-nav">
            <li class="{{ active('admin/index') }}" >
                <a href="{{ route('admin.index') }}">
                    Home
                </a>
            </li>
            <li class="{{ active('admin/assistence*') }}">
                <a href="{{ route('auth-google') }}" >
                    Assistências
                </a>
            </li>
            <li class="{{ active('admin/assistence-requests*') }}">
                <a href="{{ route('assistence-request.index') }}" >
                    Aprovar assistências
                </a>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">Cadastros <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('type-product.index') }}" >Tipos de Produto</a></li>
                    <li><a href="{{ route('brands-attended.index') }}" >Marcas Atendidas</a></li>
                </ul>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="#"></a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">{{ words($current_user->name, 2,'') }} <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{{ route('auth.logout') }}" >Sair</a></li>
                </ul>
            </li>
        </ul>
    </div>
  </div>
</div>

resources/views/layouts/navbarApp.blade.php
<div class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-inverse-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand text-bold" href="{{ url('index') }}">Let's Repair</a>
    </div>
    <div class="navbar-collapse collapse navbar-inverse-collapse">
      <ul class="nav navbar-nav">
        <li class="{{ active('admin/assistence*') }}">
            <a href="{{ route('search-assistence.index') }}" >
                Pesquisar Assistências
            </a>
        </li>
        <li class="{{ active('admin/assistence-requests*') }}">
            <a href="{{ route('assistence-solicitation.create') }}" >
                Cadastrar minha Empresa
            </a>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{{ route('auth.login') }}"><i class="fa fa-sign-in text-lg"></i></a></li>
      </ul>
    </div>
  </div>
</div>